version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: strava-mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 10
      start_period: 10s

  grafana:
    image: grafana/grafana:latest
    container_name: strava-grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: {}
  grafana_data: {}
